config/routes.rb
Rails.application.routes.draw do
  resources :todos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  get '/users', to: 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
  broadcasts
  after_destroy_commit { broadcast_remove_to "todos" }
  after_update_commit { broadcast_append_to "todos" }
  validates :title, presence: true
  enum status: { incomplete: 0, complete: 1 }

end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]

  # GET /todos or /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1 or /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.turbo_stream
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully created." }
      else
        format.turbo_stream {
          render turbo_stream: turbo_stream
          .replace("#{helpers.dom_id(@todo)}_form",
          partial: "form",
          locals: { todo: @todo})
        }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully updated." }
      else
        format.turbo_stream {
          render turbo_stream: turbo_stream
          .replace("#{helpers.dom_id(@todo)}_form",
          partial: "form",
          locals: { todo: @todo})
        }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove("#{helpers.dom_id(@todo)}_item") }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:title, :status)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if params[:query].present?
      @users = User.where("name like? or email like?", "%#{params[:query]}%", "%#{params[:query]}%")
    else
      @users = User.all
    end

    respond_to do |format|
      if turbo_frame_request? && turbo_frame_request_id == "search"
        format.html { render partial: "users_table", locals: { users: @users } }
      else
        format.html
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/home/index.html.erb
<h1>Home here</h1>
<div data-controller="hello">
  <input data-hello-target="name" />
  <button data-action="click->hello#greet">Say Hi</button>
  <span data-hello-target="output"></span>
</div>


<br><br>
<%= 
  link_to "External", "https://google.com.br",
  data: {
    controller: 'sweetalert',
    action: 'click->sweetalert#showAlert',
    sweetalert_title_value: 'Are you sure?'
  } 
  %>

<br><br><br>

<div data-controller="slideshow">
  <button data-action="slideshow#previous"> ← </button>
  <button data-action="slideshow#next"> → </button>

  <div data-slideshow-target="slide">🐵</div>
  <div data-slideshow-target="slide">🙈</div>
  <div data-slideshow-target="slide">🙉</div>
  <div data-slideshow-target="slide">🙊</div>

  <%= link_to "Users", users_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Js</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: todo, id: "#{dom_id(todo)}_form") do |form| %>
  <% if todo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-2">
    <%= form.label :title, style: "display: block", class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div>
    <%= form.submit class: 'btn btn-success'  %>
  </div>
<% end %>

app/views/todos/_todo.html.erb
<div id="<%= "#{dom_id(todo)}_item" %>">
  <%= turbo_frame_tag dom_id(todo) do %>
    <p>
      <strong>Title:</strong>
      <%= link_to todo.title, edit_todo_path(todo) %>
      
      <% if todo.complete? %>
        <%= button_to "Mark incomplete", 
          todo_path(todo, todo: { status: 'incomplete' }),
          method: :patch,
          class: "btn btn-success"
        %>
      <% else %>
        <%= button_to "Mark complete",
          todo_path(todo, todo: { status: 'complete' }),
          method: :patch,
          class: "btn btn-secondary"
        %>
      <% end %>

      <%= button_to "Delete", todo_path(todo), method: :delete, class: "btn btn-danger" %>
    </p>
  <% end %>
</div>

app/views/todos/create.turbo_stream.erb
<%= turbo_stream.prepend "todos" do %>
  <%= render "todo", todo: @todo %>
<% end %>

<%= turbo_stream.replace "#{dom_id(Todo.new)}_form" do %>
  <%= render "form", todo: Todo.new %>
<% end %>

app/views/todos/edit.html.erb
<%= turbo_frame_tag dom_id(@todo) do %>
  <%= render "form", todo: @todo %>
<% end %>

app/views/todos/index.html.erb
<p style="color: green"><%= notice %></p>


<div class="container">
  <div class="col-md-6 mx-auto">
    <h1 class="text-center text-primary">Your Todos</h1>
    <h4 class="text-success">Create a new</h4>
    <%= render "form", todo: Todo.new %>
    
    <div class="mt-5">
      <h4 class="text-success">List</h4>
      <%= turbo_stream_from "todos" %>
        <div id="todos">
          <%= render @todos %>
        </div>
    </div>
  </div>
</div>

app/views/todos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @todo %>

<div>
  <%= link_to "Edit this todo", edit_todo_path(@todo) %> |
  <%= link_to "Back to todos", todos_path %>

  <%= button_to "Destroy this todo", @todo, method: :delete %>
</div>

app/views/users/_users_table.html.erb
  <%= turbo_frame_tag "search" do %>
    <table class="table mt-5">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Email</th>
        </tr>
      </thead>
      <tbody>
        <% users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>

app/views/users/index.html.erb
<div class="container">
  <h1>Usuários</h1>
  
  <%= form_with url: users_path,
    method: :get,
    data: {
      turbo_frame: 'search',
      controller: 'search',
      action: 'keyup->search#perform'
    } do |f|  %>
    <%= f.label :query, "Search for:", class: "form-label" %>
    <%= f.text_field :query, class: "form-control", value: params[:query] %>
  <% end %>
  
  <%= render "users_table", users: @users %>
</div>